AWSTemplateFormatVersion: '2010-09-09'

Description: This template deploys your own SuSE Linux Enterprise server and configures an Apache webserver with your own coustom index page

Parameters:
  YourName:
    Description: Enter your name
    Type: String
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: SubnetId of an existing subnet (for the primary network) in your
      Virtual Private Cloud (VPC)
    ConstraintDescription: must be an existing subnet in the selected Virtual Private Cloud.
Resources:
  MyWebServerGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VpcId
      GroupDescription: Allow access to webserver
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      
  MyWebServer:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-04a615d193c180659
      Tags:
      - Key: Name
        Value: MyWebServer
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'True'
          DeleteOnTermination: 'True'
          SubnetId:
            Ref: SubnetId
          DeviceIndex: '0'
          GroupSet:
          - Ref: MyWebServerGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          zypper --non-interactive --quiet in apache2 apache2-example-pages
          systemctl start apache2
          systemctl enable apache2
          echo "<html><body><h1>${YourName} Public web site</h1></body></html>" > /srv/www/htdocs/index.html
Outputs:
  WebServerURL:
    Description: Your Webserver URL
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - MyWebServer
          - PublicIp